version: "3"

services:
  api:
    container_name: "blocked-cpf-api"
    build: .
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - api-db
    depends_on:
      - "db"

  db:
    image: postgres:13.4-buster
    container_name: "blocked-cpf-db"
    hostname: ${DB_HOST}
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_BASE}
    ports:
      - "5432:5432"
    networks:
      - api-db

networks:
  api-db:
      driver: bridge